books/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.BookHome.as_view(), name="home"),
    path("about/", views.about, name="about"),
    path("show_book/<slug:book_slug>/", views.ShowBook.as_view(), name="book"),
    path("addbook/", views.AddBook.as_view(), name="add_book"),
    path("contact/", views.contact, name="contact"),
    path("login/", views.login, name="login"),
    path("genre/<slug:genre_slug>/", views.BookGenres.as_view(), name="genre"),
    path("tag/<slug:tag_slug>/", views.BookTags.as_view(), name="tags"),
    path("edit/<int:pk>/", views.EditBookView.as_view(), name="edit"),
]

sitebook/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from sitebook import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("books.urls")),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Админка"
admin.site.index_title = "Книгиии"

users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("register/", views.RegisterUser.as_view(), name="register"),
    path("profile/", views.UserProfile.as_view(), name="profile"),
    path(
        "password-change/", views.UserPasswordChange.as_view(), name="password_change"
    ),
    path(
        "password-change-done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),

    path("password-reset/",
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name="password_reset"),
    path("password-reset-done/", PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name="password_reset_done"),
    path("password-reset/<uidb64>/<token>/",
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete"),
         ),
         name="password_reset_confirm"),

    path("password-reset/complete/",
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name="password_reset_complete"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    photo = models.ImageField(upload_to="users/%Y/%m/%d", blank=True, null=True, verbose_name="Аватарка")
    birthday = models.DateField(blank=True, null=True, verbose_name="Дата рождения")

users/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    UserCreationForm,
    UsernameField,
)
from django.core.exceptions import ValidationError


class LoginUserForm(AuthenticationForm):
    username = UsernameField(
        label="Имя пользователя", widget=forms.TextInput(attrs={"class": "form-input"})
    )
    password = forms.CharField(
        label="Пароль", widget=forms.PasswordInput(attrs={"class": "form-input"})
    )

    class Meta:
        model = get_user_model()
        fields = ("username", "password")


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )
        labels = {
            "email": "E-mail",
            "first_name": "Имя",
            "last_name": "Фамилия",
        }
        widgets = {
            "email": forms.TextInput(attrs={"class": "form-input"}),
            "first_name": forms.TextInput(attrs={"class": "form"}),
            "last_name": forms.TextInput(attrs={"class": "form"}),
        }

    username = UsernameField(
        label="Логин", widget=forms.TextInput(attrs={"class": "form-input"})
    )
    password1 = forms.CharField(
        max_length=255, label="Пароль", widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label="Повторите пароль",
        widget=forms.PasswordInput(attrs={"class": "form-input"}),
    )

    def clean_email(self):
        email = self.cleaned_data["email"]

        if get_user_model().objects.filter(email=email).exists():
            raise ValidationError("Такой email уже существует")
        return email


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "photo",
            "birthday",
        )
        labels = {
            "email": "E-mail",
            "first_name": "Имя",
            "last_name": "Фамилия",
        }
        widgets = {
            "email": forms.TextInput(attrs={"class": "form-input"}),
            "first_name": forms.TextInput(attrs={"class": "form"}),
            "last_name": forms.TextInput(attrs={"class": "form"}),
        }

    username = UsernameField(
        label="Имя пользователя",
        widget=forms.TextInput(attrs={"class": "form-input"}),
        disabled=True,
    )
    email = forms.CharField(
        label="E-mail",
        widget=forms.TextInput(attrs={"class": "form-input"}),
        disabled=True,
    )
    current_year = datetime.now().year
    birthday = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(current_year - 100, current_year - 5))))


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Старый пароль", widget=forms.PasswordInput(attrs={"class": "form-input"})
    )
    new_password1 = forms.CharField(
        label="Новый пароль", widget=forms.PasswordInput(attrs={"class": "form-input"})
    )
    new_password2 = forms.CharField(
        label="Повторите новый пароль",
        widget=forms.PasswordInput(attrs={"class": "form-input"}),
    )

users/views.py
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from sitebook import settings
from .forms import (
    LoginUserForm,
    RegisterUserForm,
    UserPasswordChangeForm,
    UserProfileForm,
)


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = "users/login.html"
    extra_context = {"title": "Авторизация"}


def logout_user(request: HttpRequest) -> HttpResponse:
    logout(request)
    return HttpResponseRedirect(reverse("home"))


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = "users/register.html"
    extra_context = {"title": "Регистрация"}
    success_url = reverse_lazy("users:login_user")


class UserProfile(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserProfileForm
    template_name = "users/profile.html"
    extra_context = {"title": "Профиль пользователя", "default_image": settings.DEFAULT_USER_IMAGE}

    def get_success_url(self):
        return reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {"title": "Смена пароля"    }

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Авторизация</h1>

<form action="" method="POST">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p>
        <label class="form-label" for="{{ f.id_for_label }}">
            {{ f.label }}
        </label>
        {{ f }}
    </p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Войти</button>
</form>

{% endblock %}

users/templates/users/password_change_done.html
{% extends "base.html" %}

{% block content %}
<h1>Пароль успешно изменен</h1>

<p>
    Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль</a>
</p>
{% endblock %}

users/templates/users/password_change_form.html
{% extends "base.html" %}

{% block content %}
<h1>Изменение пароля</h1>

<form method="POST">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p>
        <label class="form-label" for="{{ f.id_for_label }}">
            {{ f.label }}:
        </label>
        {{ f }}
    </p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p>
        <button type="submit">
            Сменить пароль
        </button>
    </p>
</form>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
<h1>Пароль изменен</h1>
<p>Пароль успешно изменен. Используйте его для <a href="{% url 'users:login_user' %}">входа в систему</a></p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<h1>Новый пароль</h1>

<form method="POST">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p>
        <label class="form-label" for="{{ f.id_for_label }}">
            {{ f.label }}:
        </label>
        {{ f }}
    </p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p>
        <button type="submit">
            Сохранить
        </button>
    </p>
</form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
<h1>Сброс пароля</h1>
<p>На Ваш email отправлена инструкция по восставновлению пароля</p>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends "base.html" %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="POST">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p>
        <label class="form-label" for="{{ f.id_for_label }}">
            {{ f.label }}:
        </label>
        {{ f }}
    </p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p>
        <button type="submit">
            Сбросить пароль
        </button>
    </p>
</form>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block content %}
<h1>Профиль пользователя {{ user.username }}</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if user.photo %}
    <p>
        <img src="{{ user.photo.url }}" alt="">
    </p>
    {% else %}
    <p>
        <img src="{{ default_image }}" alt="">
    </p>
    {% endif %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p>
        <label class="form-label" for="{{ f.id_for_label }}">
            {{ f.label }}:
        </label>
        {{ f }}
    </p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p>
        <button type="submit">
            Сохранить
        </button>
    </p>
</form>
<hr>
<p>
    <a href="{% url 'users:password_change' %}">Сменить пароль</a>
</p>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}


{% block content %}
<h1>
    Регистрация
</h1>

<form method="POST">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p>
        <label class="form-label" for="{{ f.id_for_label }}">
            {{ f.label }}
        </label>
        {{ f }}
    </p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p>
        <button type="submit">Регистрация</button>
    </p>
</form>
{% endblock %}

users/templates/users/register_done.html
{% extends "base.html" %}

{% block content %}
<h1>
    Добро пожаловать!
</h1>

<p>
    Регистрация прошла успешно. Для входа в систему необходимо авторизоваться по
    <a href="{% url 'users:login_user' %}">ссылке</a>
</p>
{% endblock %}